#!/usr/bin/env python3
# =============================================================================
# [🐍 Python Script] [🪟 CustomTkinter GUI] [🔁 Git Repository Bulk Update]
# =============================================================================
"""
Repository Bulk

What this does (single-file GUI replacement for your 2 scripts):
- Refresh tab:
  - Scan configured root folders for git repositories (folders containing ".git").
  - Extract an SSH key per repo from:
      1) repo .git/config (IdentityFile / PuTTYKeyFile / sshCommand -i ...)
      2) TortoiseGit per-project registry settings (Windows only)
      3) TortoiseGit global registry settings (Windows only)
      4) fallback default_ssh_key from refresh config
  - Writes the mapping { repo_path: ssh_key_path } to repository_manifest.json (hard-coded next to the script)

- Pull tab:
  - Loads the repo list JSON generated by refresh.
  - Applies optional allowed_roots / disallowed_roots filtering (pull config).
  - Runs `git pull --ff-only` for each repo (skips unborn repos with no commits).
  - Uses per-repo SSH key by setting:
      GIT_SSH_COMMAND = plink -i "<key>"
    (matches your existing pull script behavior; Windows-oriented)

Folder layout assumption (matches your tree):
<repo_bulk_dir>/
  repository_bulk_gui.py          <-- this file
  repository_bulk_refresh.py
  repository_bulk_pull.py
  config/
    repository_bulk_refresh.json
    repository_bulk_pull.json
    repository_bulk_list.json
    default/
      repository_bulk_refresh.json
      repository_bulk_pull.json

Template compatibility:
- If your default template filenames differ, this script also checks legacy names:
    config/default/repo_list_refresh.json
    config/default/repo_list_pull.json

Dependencies:
- customtkinter

Install:
  pip install customtkinter

Run:
  python repository_bulk_gui.py
"""

from __future__ import annotations

import importlib.util
import json
import os
import queue
import re
import shutil
import subprocess
import sys
import threading
import time
import typing as t
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

# =============================================================================
# packages_custom (vendored for this standalone repository)
# =============================================================================

_PACKAGES_CUSTOM_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "packages_custom"))
_MANIFEST_HELPER_PATH = os.path.join(_PACKAGES_CUSTOM_DIR, "cure-repo-manifest.py")


def _load_manifest_helper():
  """Load the vendored helper whose kebab-case filename is not importable normally."""
  spec = importlib.util.spec_from_file_location("cure_repo_manifest", _MANIFEST_HELPER_PATH)
  if spec is None or spec.loader is None:
    raise ImportError(f"Unable to load repository manifest helper: {_MANIFEST_HELPER_PATH}")
  module = importlib.util.module_from_spec(spec)
  sys.modules[spec.name] = module
  spec.loader.exec_module(module)
  return module


_manifest_helper = _load_manifest_helper()
ManifestV2 = _manifest_helper.ManifestV2
RepoState = _manifest_helper.RepoState
load_manifest_v2 = _manifest_helper.load_manifest_v2
now_iso = _manifest_helper.now_iso
repos_by_path = _manifest_helper.repos_by_path
save_manifest_v2 = _manifest_helper.save_manifest_v2
ts_short = _manifest_helper.ts_short
upsert_repo = _manifest_helper.upsert_repo

try:
  import customtkinter as ctk
except Exception as e:
  raise SystemExit(
    "\n".join([
      "Missing dependency: customtkinter",
      "",
      "Install:",
      "  pip install customtkinter",
      "",
      f"Original error: {e}",
    ])
  )

import tkinter as tk
from tkinter import filedialog, messagebox, ttk
import tkinter.font as tkfont

# =============================================================================
# UI Theme Bridge (CustomTkinter -> ttk/tk)
# =============================================================================

# Bump these to taste.
_UI_FONT_TTK_BODY = 13
_UI_FONT_TTK_HEADING = 14
_UI_FONT_ENTRY = 13
_UI_FONT_TEXTBOX = 13
_UI_FONT_LISTBOX = 13

def _ttk_font(size: int, *, weight: str = "normal"):
  """Create a Tk font tuple suitable for ttk widgets."""
  return ("Segoe UI", size, weight)

def _ctk_color(c):
  """Resolve a CTk theme color (single or light/dark tuple) into a concrete color string."""
  if isinstance(c, (tuple, list)):
    # index 1 = dark mode
    return c[1]
  return c

def apply_dark_ttk_treeview_style(root) -> None:
  """Force ttk.Treeview to visually match CustomTkinter dark mode."""
  style = ttk.Style(master=root)

  try:
    style.theme_use("default")
  except Exception:
    pass

  bg     = _ctk_color(ctk.ThemeManager.theme["CTkFrame"]["fg_color"])
  bg_alt = _ctk_color(ctk.ThemeManager.theme["CTkFrame"]["top_fg_color"])
  fg     = _ctk_color(ctk.ThemeManager.theme["CTkLabel"]["text_color"])
  sel_bg = _ctk_color(ctk.ThemeManager.theme["CTkButton"]["hover_color"])
  sel_fg = fg

  style.configure(
    "Treeview",
    background=bg,
    fieldbackground=bg,
    foreground=fg,
    rowheight=30,
    borderwidth=0,
    relief="flat",
    font=_ttk_font(_UI_FONT_TTK_BODY),
  )

  style.map(
    "Treeview",
    background=[("selected", sel_bg)],
    foreground=[("selected", sel_fg)],
  )

  style.configure(
    "Treeview.Heading",
    background=bg_alt,
    foreground=fg,
    relief="flat",
    borderwidth=0,
    font=_ttk_font(_UI_FONT_TTK_HEADING, weight="bold"),
  )

  style.map(
    "Treeview.Heading",
    background=[("active", bg_alt)],
    foreground=[("active", fg)],
  )

def apply_dark_ttk_scrollbar_style(root) -> None:
  """Dark-mode ttk.Scrollbar styling to match CustomTkinter theme."""
  style = ttk.Style(master=root)

  try:
    style.theme_use("default")
  except Exception:
    pass

  bg       = _ctk_color(ctk.ThemeManager.theme["CTkFrame"]["fg_color"])
  accent   = _ctk_color(ctk.ThemeManager.theme["CTkButton"]["fg_color"])
  accent_h = _ctk_color(ctk.ThemeManager.theme["CTkButton"]["hover_color"])

  def _configure_scrollbar_style(style_name: str) -> None:
    style.configure(
      style_name,
      background=accent,
      troughcolor=bg,
      bordercolor=bg,
      lightcolor=accent,
      darkcolor=accent,
      arrowcolor="#9aa4af",
      relief="flat",
      borderwidth=0,
      arrowsize=18,
      width=16,
    )

    style.map(
      style_name,
      background=[
        ("active", accent_h),
        ("!active", accent),
      ],
      arrowcolor=[
        ("active", "#9aa4af"),
        ("pressed", "#9aa4af"),
        ("!active", "#9aa4af"),
        ("disabled", "#666666"),
      ],
    )

  _configure_scrollbar_style("Dark.Vertical.TScrollbar")
  _configure_scrollbar_style("Dark.Horizontal.TScrollbar")

# Windows-only registry support (gracefully disabled elsewhere)
try:
  import winreg  # type: ignore
  _HAS_WINREG = True
except Exception:
  winreg = None  # type: ignore
  _HAS_WINREG = False

# =============================================================================
# Windows Taskbar Identity (AppUserModelID) + Window Icon
# =============================================================================

# Unique per-app ID for Windows taskbar grouping / pinning behavior.
# Change the suffix if you ship another variant (v3, etc).
APP_USER_MODEL_ID = "CureInteractive.RepositoryBulk.v2"

def set_windows_app_user_model_id(app_user_model_id: str) -> None:
  """
  Windows-only: set a stable AppUserModelID for correct taskbar grouping and icon behavior.

  Must be called BEFORE creating the Tk/CTk root window for best results.

  On non-Windows platforms this is a no-op.
  """
  if os.name != "nt":
    return
  if not app_user_model_id:
    return

  try:
    import ctypes  # stdlib
    ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(app_user_model_id)
  except Exception:
    # Best-effort only; never break app startup
    pass

# =============================================================================
# Window Icon (title bar / taskbar best-effort)
# =============================================================================

def set_window_icon(root, ico_path: str, png_path: str) -> None:
  """
  Best-effort window icon:
  - Windows: root.iconbitmap(.ico)
  - Linux/macOS: root.iconphoto(.png)
  Keeps a reference to PhotoImage to avoid GC.
  """
  ico_abs = os.path.abspath(ico_path) if ico_path else ""
  png_abs = os.path.abspath(png_path) if png_path else ""

  # Windows: .ico
  try:
    if ico_abs and os.path.isfile(ico_abs):
      root.iconbitmap(ico_abs)
  except Exception:
    pass

  # Cross-platform: .png
  try:
    if png_abs and os.path.isfile(png_abs):
      img = tk.PhotoImage(file=png_abs)
      root.iconphoto(True, img)
      root._iconphoto_ref = img  # prevent garbage collection
  except Exception:
    pass


# =============================================================================
# ANSI (kept for parity; GUI log is plain text, but we keep tags consistent)
# =============================================================================

ANSI_RED = "\033[91m"
ANSI_YELLOW = "\033[93m"
ANSI_BLUE = "\033[94m"
ANSI_GREEN = "\033[92m"
ANSI_RESET = "\033[0m"


# =============================================================================
# Paths + JSON
# =============================================================================

_SCRIPT_DIR = os.path.abspath(os.path.dirname(__file__))

# Root-level config files (no config/ directory)
_CONFIG_DEFAULT_JSON = os.path.join(_SCRIPT_DIR, "config-default.json")
_CONFIG_JSON = os.path.join(_SCRIPT_DIR, "config.json")
_CONFIG_RESTORE_JSON = os.path.join(_SCRIPT_DIR, "config_restore.json")

# Root-level repo list / manifest (hard-coded output)
_REPOSITORY_MANIFEST_JSON = os.path.join(_SCRIPT_DIR, "repository_manifest.json")


def _abs_from_script(path: str) -> str:
  if not path:
    return path
  if os.path.isabs(path):
    return os.path.abspath(path)
  return os.path.abspath(os.path.join(_SCRIPT_DIR, path))


def path_safe(path: str) -> str:
  """
  Normalize + absolute + forward slashes.
  IMPORTANT: relative paths are resolved relative to THIS script's folder.
  """
  if not path:
    return path
  return os.path.normpath(_abs_from_script(path)).replace("\\", "/")


def read_json(path: str, *, required: bool = True, default: Any = None) -> Any:
  if not os.path.exists(path):
    if required:
      raise FileNotFoundError(path)
    return default
  with open(path, "r", encoding="utf-8") as f:
    return json.load(f)


def write_json(path: str, data: Any, *, indent: int = 2) -> None:
  parent = os.path.dirname(path)
  if parent:
    os.makedirs(parent, exist_ok=True)
  with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=indent)


def _copy_if_missing(dst: str, src: str, *, overwrite: bool = False) -> bool:
  os.makedirs(os.path.dirname(dst), exist_ok=True)
  if os.path.exists(dst) and not overwrite:
    return False
  if not os.path.exists(src):
    raise FileNotFoundError(src)
  shutil.copy2(src, dst)
  return True


def _default_template_candidates(mode: str) -> List[str]:
  """
  Support both your current tree naming and an older naming variant.
  """
  if mode == "refresh":
    return [
      os.path.join(_DEFAULT_DIR, "repository_bulk_refresh.json"),
      os.path.join(_DEFAULT_DIR, "repo_list_refresh.json"),
    ]
  if mode == "pull":
    return [
      os.path.join(_DEFAULT_DIR, "repository_bulk_pull.json"),
      os.path.join(_DEFAULT_DIR, "repo_list_pull.json"),
    ]
  return []


def ensure_defaults(*, overwrite: bool = False) -> None:
  """
  Ensure root-level config.json exists by copying config-default.json if missing.
  """
  if not os.path.exists(_CONFIG_DEFAULT_JSON):
    raise FileNotFoundError(_CONFIG_DEFAULT_JSON)

  if not os.path.exists(_CONFIG_JSON) or overwrite:
    _copy_if_missing(_CONFIG_JSON, _CONFIG_DEFAULT_JSON, overwrite=overwrite)


def preflight(mode: str) -> None:
  """
  Validate required root-level files for each operation.
  """
  if mode == "refresh":
    if not os.path.exists(_CONFIG_JSON):
      raise FileNotFoundError(_CONFIG_JSON)

  elif mode == "pull":
    if not os.path.exists(_CONFIG_JSON):
      raise FileNotFoundError(_CONFIG_JSON)
    if not os.path.exists(_REPOSITORY_MANIFEST_JSON):
      raise FileNotFoundError(_REPOSITORY_MANIFEST_JSON)

  else:
    raise ValueError(f"Unknown mode: {mode}")


# =============================================================================
# Refresh: scan repos + extract ssh keys (matches repository_bulk_refresh.py)
# =============================================================================

def should_skip_dir(dirname: str, ignore_prefixes: List[str]) -> bool:
  return any(dirname.startswith(prefix) for prefix in ignore_prefixes)


def _parse_identity_from_sshcommand(value: str) -> str:
  # -i "path" OR -i path
  m = re.search(r'(?:^|\s)-i\s+(?:"([^"]+)"|(\S+))', value)
  if not m:
    return ""
  return (m.group(1) or m.group(2) or "").strip()


def extract_ssh_key_from_config(repo_path: str) -> str:
  config_path = os.path.join(repo_path, ".git", "config")
  if not os.path.exists(config_path):
    return ""

  try:
    with open(config_path, "r", encoding="utf-8") as f:
      for raw in f:
        line = raw.strip()
        lower = line.lower()

        if "identityfile" in lower and "=" in line:
          return line.split("=", 1)[-1].strip().strip('"').strip("'")

        if "puttykeyfile" in lower and "=" in line:
          return line.split("=", 1)[-1].strip().strip('"').strip("'")

        if "sshcommand" in lower and "=" in line:
          value = line.split("=", 1)[-1].strip().strip('"').strip("'")
          found = _parse_identity_from_sshcommand(value)
          if found:
            return found
  except OSError:
    return ""

  return ""


def _registry_project_key_variants(repo_path: str) -> List[str]:
  r"""
  TortoiseGit stores keys under:
    HKCU\Software\TortoiseGit\Projects\<path>
  """
  p = repo_path.rstrip("\\/").replace("/", "\\")
  variants = {p, p.lower()}

  if len(p) >= 2 and p[1] == ":":
    variants.add(p[0].upper() + p[1:])
    variants.add(p[0].lower() + p[1:])
    variants.add((p[0].upper() + p[1:]).lower())
    variants.add((p[0].lower() + p[1:]).lower())

  return list(variants)


def extract_ssh_key_from_registry(repo_path: str) -> str:
  if not _HAS_WINREG:
    return ""

  for variant in _registry_project_key_variants(repo_path):
    key_path = f"Software\\TortoiseGit\\Projects\\{variant}"
    try:
      with winreg.OpenKey(winreg.HKEY_CURRENT_USER, key_path) as key:  # type: ignore
        for i in range(0, 50):
          try:
            name, value, _ = winreg.EnumValue(key, i)  # type: ignore
            if name.lower() in {"keyfile", "sshkey", "puttykey", "identityfile"}:
              return value
          except OSError:
            break
    except FileNotFoundError:
      continue
    except OSError:
      continue

  return ""


def extract_ssh_key_from_global_settings() -> str:
  if not _HAS_WINREG:
    return ""
  try:
    with winreg.OpenKey(winreg.HKEY_CURRENT_USER, r"Software\TortoiseGit") as key:  # type: ignore
      for i in range(0, 50):
        try:
          name, value, _ = winreg.EnumValue(key, i)  # type: ignore
          if name.lower() in {"puttykey", "sshkey", "keyfile", "identityfile"}:
            return value
        except OSError:
          break
  except FileNotFoundError:
    pass
  except OSError:
    pass
  return ""


def find_git_repos_with_keys(
  root_path: str,
  default_key: str,
  ignore_prefixes: List[str],
  log_fn,
) -> Dict[str, str]:
  repo_keys: Dict[str, str] = {}

  for dirpath, dirnames, _filenames in os.walk(root_path):
    dirnames[:] = [d for d in dirnames if not should_skip_dir(d, ignore_prefixes)]

    if ".git" in dirnames:
      repo_path = path_safe(dirpath)
      ssh_key = (
        extract_ssh_key_from_config(repo_path)
        or extract_ssh_key_from_registry(repo_path)
        or extract_ssh_key_from_global_settings()
        or default_key
      )
      repo_keys[repo_path] = path_safe(ssh_key) if ssh_key else ""
      dirnames[:] = []
      if ssh_key:
        log_fn("info", f"🔑 Found repo: {repo_path}  (key: {repo_keys[repo_path]})")
      else:
        log_fn("warn", f"🔑 Found repo: {repo_path}  (key: <none>)")

  return repo_keys


# =============================================================================
# Pull: load list + filter + git pull --ff-only (matches repository_bulk_pull.py)
# =============================================================================

def is_repo_unborn(repo_path: str) -> bool:
  try:
    subprocess.run(
      ["git", "-C", repo_path, "rev-parse", "--verify", "HEAD"],
      check=True,
      stdout=subprocess.PIPE,
      stderr=subprocess.PIPE,
      text=True,
    )
    return False
  except subprocess.CalledProcessError:
    return True


def is_repo_bare(repo_path: str) -> bool:
  """
  True if the target path is a *bare* git repository (no working tree).

  This is treated as a non-error "skipped" state for this tool, since
  `git pull` requires a work tree.
  """
  try:
    r = subprocess.run(
      ["git", "-C", repo_path, "rev-parse", "--is-bare-repository"],
      check=True,
      stdout=subprocess.PIPE,
      stderr=subprocess.PIPE,
      text=True,
    )
    return (r.stdout or "").strip().lower() == "true"
  except Exception:
    return False


def git_pull_ff_only(repo_path: str, ssh_key: str) -> Tuple[bool, Optional[str], bool]:
  """
  Returns: (success, error_msg, changed)

  Notes:
  - Bare repos are *skipped* (non-error) because `git pull` requires a work tree.
  - Unborn HEAD repos are *skipped* (non-error) because there are no commits/branches yet.
  """
  env = os.environ.copy()
  if ssh_key:
    env["GIT_SSH_COMMAND"] = f'plink -i "{ssh_key}"'

  if is_repo_bare(repo_path):
    return False, "Bare repository (no work tree). Skipping.", False

  if is_repo_unborn(repo_path):
    return False, "Unborn HEAD (no commits). Skipping.", False

  try:
    result = subprocess.run(
      ["git", "-C", repo_path, "pull", "--ff-only"],
      check=True,
      stdout=subprocess.PIPE,
      stderr=subprocess.PIPE,
      text=True,
      env=env,
    )
    out = (result.stdout or "").strip()
    changed = ("Already up to date." not in out) and ("Already up-to-date." not in out)
    return True, None, changed
  except subprocess.CalledProcessError as e:
    stderr = (e.stderr or "").strip()
    stdout = (e.stdout or "").strip()
    msg = stderr or stdout or str(e)
    return False, msg, False


def load_repo_manifest_for_pull(repo_json: str, pull_filters_json: str) -> Tuple[ManifestV2, List[RepoState]]:
  """
  Loads repository_manifest.json (any supported format) and returns:
    (manifest_v2, filtered_repos)

  Filtering is driven by config.json (filters.allowed_roots / filters.disallowed_roots)
  with back-compat to pull.allowed_roots / pull.disallowed_roots.
  """
  manifest: ManifestV2 = load_manifest_v2(repo_json)

  cfg = read_json(pull_filters_json, required=True)
  filters_cfg = cfg.get("filters", {}) if isinstance(cfg, dict) else {}
  if not filters_cfg:
    filters_cfg = cfg.get("pull", {}) if isinstance(cfg, dict) else {}

  allowed_prefixes = [path_safe(p) for p in filters_cfg.get("allowed_roots", []) if isinstance(p, str)]
  disallowed_prefixes = [path_safe(p) for p in filters_cfg.get("disallowed_roots", []) if isinstance(p, str)]

  out: List[RepoState] = []
  for r in (manifest.get("repos", []) or []):
    repo_path = path_safe(str(r.get("path", "") or ""))
    if not repo_path:
      continue

    if any(repo_path.startswith(disallowed) for disallowed in disallowed_prefixes):
      continue

    if allowed_prefixes and not any(repo_path.startswith(allowed) for allowed in allowed_prefixes):
      continue

    # Normalize fields
    r["path"] = repo_path
    r["ssh_key"] = path_safe(str(r.get("ssh_key", "") or ""))
    if not r.get("message"):
      r["message"] = "Idle"
    if not r.get("phase"):
      r["phase"] = "idle"

    out.append(r)

  return manifest, out


# =============================================================================
# GUI
# =============================================================================

@dataclass
class RefreshSettings:
  scan_roots: List[str]
  ignore_prefixes: List[str]
  default_ssh_key: str


@dataclass
class PullSettings:
  allowed_roots: List[str]
  disallowed_roots: List[str]


APP_TITLE = "Git Repository Update - Cure Interactive"

class App(ctk.CTk):
  def __init__(self):
    super().__init__()

    set_window_icon(
      self,
      os.path.join(_SCRIPT_DIR, "icon.ico"),
      os.path.join(_SCRIPT_DIR, "icon.png"),
    )

    self.title(APP_TITLE)
    self.geometry("1200x760")
    self.minsize(1100, 700)

    # Make ttk widgets (Treeview/Scrollbar) match CustomTkinter theme.
    apply_dark_ttk_treeview_style(self)
    apply_dark_ttk_scrollbar_style(self)

    # Shared fonts (bumped sizes).
    self._font_entry = ctk.CTkFont(size=_UI_FONT_ENTRY)
    self._font_textbox = ctk.CTkFont(size=_UI_FONT_TEXTBOX)

    self._log_q: "queue.Queue[Tuple[str, str]]" = queue.Queue()
    self._ui_q: "queue.Queue[Tuple[str, Any]]" = queue.Queue()

    self._worker: Optional[threading.Thread] = None
    self._worker_stop = threading.Event()

    # In-memory repo state keyed by absolute repo path
    self._repo_state_by_path: Dict[str, RepoState] = {}

    # If set, _do_pull() will only operate on these repo paths (Pull Selected).
    self._pull_only_paths: Optional[set[str]] = None

    self.refresh_settings = self._load_refresh_settings_safe()
    self.pull_settings = self._load_pull_settings_safe()

    self._build_ui()
    self._pump_queues()

    self._bootstrap_if_needed_initial()

    # Repo table is seeded by _bootstrap_if_needed_initial() from repository_manifest.json (if present).

  def _install_treeview_cell_tooltip(self, tree: "ttk.Treeview") -> None:
    """
    Treeview cell tooltip: hover shows the currently-hovered cell value.
    Mirrors the behavior used in gitea_repository_backup.py.
    """
    tip_state = {
      "win": None,
      "lbl": None,
      "font": None,  # cached tk Font for tooltip
      "last": None,  # (iid, col_id, value)
    }

    def _tip_hide() -> None:
      win = tip_state.get("win")
      if win is not None:
        try:
          win.destroy()
        except Exception:
          pass
      tip_state["win"] = None
      tip_state["lbl"] = None
      tip_state["last"] = None

    def _tip_show(*, text: str, x_root: int, y_root: int) -> None:
      # Create if needed
      if tip_state["win"] is None:
        win = tk.Toplevel(self)
        win.withdraw()
        win.overrideredirect(True)
        try:
          win.attributes("-topmost", True)
        except Exception:
          pass

        bg = _ctk_color(ctk.ThemeManager.theme["CTkFrame"]["top_fg_color"])
        fg = _ctk_color(ctk.ThemeManager.theme["CTkLabel"]["text_color"])

        # Build a larger tooltip font based on the current Tk default font
        from tkinter import font as tkfont
        if tip_state["font"] is None:
          f = tkfont.nametofont("TkDefaultFont").copy()
          try:
            f.configure(size=int(f.cget("size")) + 4)
          except Exception:
            f.configure(size=14)
          tip_state["font"] = f

        lbl = tk.Label(
          win,
          text="",
          justify="left",
          padx=8,
          pady=4,
          bg=bg,
          fg=fg,
          font=tip_state["font"],
          bd=1,
          relief="solid",
        )
        lbl.pack()

        tip_state["win"] = win
        tip_state["lbl"] = lbl

      win = tip_state["win"]
      lbl = tip_state["lbl"]
      if win is None or lbl is None:
        return

      lbl.configure(text=text)

      # Offset so it doesn't sit under the mouse
      x = x_root + 14
      y = y_root + 16

      try:
        win.geometry(f"+{x}+{y}")
        win.deiconify()
      except Exception:
        pass

    def _on_hover(event) -> None:
      iid = tree.identify_row(event.y)
      col = tree.identify_column(event.x)  # "#1", "#2", ...
      if not iid or not col or col == "#0":
        _tip_hide()
        return

      cols = list(tree["columns"])
      try:
        idx = int(col[1:]) - 1
      except Exception:
        _tip_hide()
        return

      if idx < 0 or idx >= len(cols):
        _tip_hide()
        return

      col_id = cols[idx]

      try:
        val = tree.set(iid, col_id)
      except Exception:
        _tip_hide()
        return

      text_val = str(val)

      # For time columns, show raw ISO (if available) rather than the shortened display value.
      if col_id in {"seen", "pulled"}:
        try:
          row_vals = tree.item(iid, "values") or ()
          repo_path = row_vals[1] if (row_vals and len(row_vals) >= 2) else ""
          st = self._repo_state_by_path.get(repo_path) if repo_path else None
          if st:
            raw = ""
            if col_id == "seen":
              raw = str(st.get("seen_at", "") or "")
            elif col_id == "pulled":
              raw = str(st.get("pulled_at", "") or "")
            if raw:
              text_val = raw
        except Exception:
          pass

      key = (iid, col_id, text_val)

      if tip_state["last"] != key:
        tip_state["last"] = key

      _tip_show(text=text_val, x_root=event.x_root, y_root=event.y_root)

    tree.bind("<Motion>", _on_hover)
    tree.bind("<Leave>", lambda _e: _tip_hide())
    tree.bind("<ButtonPress>", lambda _e: _tip_hide())
    tree.bind("<MouseWheel>", lambda _e: _tip_hide())     # Windows
    tree.bind("<Button-4>", lambda _e: _tip_hide())       # Linux
    tree.bind("<Button-5>", lambda _e: _tip_hide())       # Linux

  def _install_treeview_context_menu(self, tree: "ttk.Treeview") -> None:
    """
    Right-click context menu for per-repo actions:
      - Pull Selected
      - Open Selected
      - Copy Repo Path(s)
      - Copy SSH Key(s)
    """
    menu = tk.Menu(self, tearoff=0)

    def _pull_selected() -> None:
      self._on_pull_selected_clicked()

    def _open_selected() -> None:
      self._on_open_selected_clicked()

    def _copy_paths() -> None:
      paths = self._get_selected_repo_paths()
      if not paths:
        return
      self._copy_to_clipboard("\n".join(paths))

    def _copy_keys() -> None:
      keys = self._get_selected_repo_keys()
      if not keys:
        return
      self._copy_to_clipboard("\n".join(keys))

    def _select_all() -> None:
      try:
        tree.selection_set(tree.get_children())
      except Exception:
        pass

    menu.add_command(label="⬇️ Pull Selected", command=_pull_selected)
    menu.add_separator()
    menu.add_command(label="📂 Open Selected", command=_open_selected)
    menu.add_separator()
    menu.add_command(label="📋 Copy Repo Path(s)", command=_copy_paths)
    menu.add_command(label="📋 Copy SSH Key(s)", command=_copy_keys)
    menu.add_separator()
    menu.add_command(label="Select All", command=_select_all)

    def _on_right_click(event) -> None:
      iid = tree.identify_row(event.y)

      # If right-clicking a row, select it (unless already part of selection)
      if iid:
        try:
          sel = set(tree.selection() or ())
          if iid not in sel:
            tree.selection_set((iid,))
        except Exception:
          pass

      try:
        menu.tk_popup(event.x_root, event.y_root)
      finally:
        try:
          menu.grab_release()
        except Exception:
          pass

    # Windows/Linux
    tree.bind("<Button-3>", _on_right_click)
    # macOS sometimes uses Button-2
    tree.bind("<Button-2>", _on_right_click)

  def _update_selection_dependent_controls(self) -> None:
    """
    Enable/disable controls that require a selection.

    This keeps Run-tab UX aligned with gitea_repository_backup’s “gold standard”:
    buttons don’t look clickable when nothing is selected.
    """
    try:
      any_sel = bool(self.tree.selection())
    except Exception:
      any_sel = False

    state = "normal" if any_sel else "disabled"

    try:
      self.btn_pull_selected.configure(state=state)
    except Exception:
      pass

    try:
      self.btn_open_selected.configure(state=state)
    except Exception:
      pass


  def _install_treeview_fit_columns(self, tree: "ttk.Treeview", frame: "ctk.CTkFrame") -> None:
    """
    Debounced “fit” behavior for the two stretch columns (repo/key).

    - Keeps fixed columns fixed.
    - Reallocates leftover width between repo/key.
    - Prevents jitter by debouncing <Configure>.
    """
    def _fit_now() -> None:
      try:
        w = int(tree.winfo_width() or 0)
      except Exception:
        return

      if w <= 0:
        return

      # Fixed columns
      fixed = 0
      for col in ("idx", "seen", "pulled", "status"):
        try:
          fixed += int(tree.column(col, "width") or 0)
        except Exception:
          pass

      # Scrollbar gutter / padding fudge (ttk varies a bit)
      gutter = 26
      avail = max(0, w - fixed - gutter)

      repo_min = 180
      key_min = 140

      if avail <= (repo_min + key_min):
        repo_w = repo_min
        key_w = key_min
      else:
        # Weight repo a little heavier than key
        repo_w = int(avail * 0.60)
        key_w = avail - repo_w
        repo_w = max(repo_w, repo_min)
        key_w = max(key_w, key_min)

      try:
        tree.column("repo", width=repo_w)
        tree.column("key", width=key_w)
      except Exception:
        pass

    def _debounced(_e=None) -> None:
      try:
        if getattr(self, "_fit_after_id", None):
          self.after_cancel(self._fit_after_id)
      except Exception:
        pass

      self._fit_after_id = self.after(120, _fit_now)

    frame.bind("<Configure>", _debounced)
    tree.bind("<Map>", _debounced)

    # Initial fit
    _debounced()

  # ---------------------------------------------------------------------------
  # Settings load/save/bootstrap
  # ---------------------------------------------------------------------------

  def _reload_settings_from_disk(self) -> None:
    """
    Reload config.json from disk, update UI widgets, and refresh Restore button state.
    """
    try:
      ensure_defaults(overwrite=False)

      self.refresh_settings = self._load_refresh_settings_safe()
      self.pull_settings = self._load_pull_settings_safe()
      self._sync_settings_to_ui()
      self._ui_update_restore_button_state()

      self._log("ok", f"🔄 Reloaded settings from: {path_safe(_CONFIG_JSON)}")
    except Exception as e:
      messagebox.showerror("Reload failed", str(e))

  def _bootstrap_if_needed_initial(self) -> None:
    try:
      ensure_defaults(overwrite=False)
    except Exception as e:
      messagebox.showerror("Error", f"Failed to ensure defaults:\n{e}")

    self.refresh_settings = self._load_refresh_settings_safe()
    self.pull_settings = self._load_pull_settings_safe()
    self._sync_settings_to_ui()
    self._ui_update_restore_button_state()

    # Fill the repo table immediately from the manifest (if present)
    self.after(0, self._seed_repo_table_on_start)

  def _seed_repo_table_on_start(self) -> None:
    """
    Populate the repo table at startup from repository_manifest.json (if present).

    Supports:
    - v2 manifest: { "version": 2, "repos": [...] }
    - v1 mapping: { "<repo_path>": "<ssh_key>", ... }
    - legacy list: [ [ "<repo_path>", "<ssh_key>" ], ... ]
    """
    try:
      manifest_path = path_safe(_REPOSITORY_MANIFEST_JSON)

      manifest: ManifestV2 = load_manifest_v2(manifest_path)
      repos = manifest.get("repos", []) or []

      self._repo_state_by_path = repos_by_path(manifest)

      # Clear + repopulate
      for iid in self.tree.get_children():
        self.tree.delete(iid)

      for r in repos:
        repo_path = path_safe(str(r.get("path", "") or ""))
        ssh_key = path_safe(str(r.get("ssh_key", "") or ""))
        status = str(r.get("message", "") or "Idle") or "Idle"
        seen = ts_short(str(r.get("seen_at", "") or ""))
        pulled = ts_short(str(r.get("pulled_at", "") or ""))

        if repo_path:
          self._tree_add_row(repo_path, ssh_key, status, idx=int(r.get("index", 0) or 0) or None, last_seen=seen, last_pull=pulled)

      try:
        self.lbl_status.configure(text=f"Idle ({len(repos)} repos loaded)")
      except Exception:
        pass

      self._log("ok", f"📋 Loaded {len(repos)} repos into table from: {manifest_path}")

    except Exception as e:
      self._log("warn", f"⚠️  Could not seed repo table from manifest: {e}")

  def _populate_repo_table_on_start(self) -> None:
    """
    Legacy hook kept for safety. Uses the new manifest-based seeding.
    """
    self._seed_repo_table_on_start()

  def _load_refresh_settings_safe(self) -> RefreshSettings:
    try:
      ensure_defaults(overwrite=False)
      cfg = read_json(_CONFIG_JSON, required=True)

      # New unified naming: "scan"
      # Back-compat: accept legacy "refresh".
      r = cfg.get("scan", {}) if isinstance(cfg, dict) else {}
      if not r:
        r = cfg.get("refresh", {}) if isinstance(cfg, dict) else {}
    except Exception:
      r = {}

    scan_roots = [s for s in r.get("scan_roots", []) if isinstance(s, str) and s.strip()]
    ignore_prefixes = [s for s in r.get("ignore_prefixes", []) if isinstance(s, str)]
    default_ssh_key = r.get("default_ssh_key", "") if isinstance(r.get("default_ssh_key", ""), str) else ""

    return RefreshSettings(
      scan_roots=scan_roots,
      ignore_prefixes=ignore_prefixes or ["$", "System Volume Information"],
      default_ssh_key=default_ssh_key,
    )

  def _load_pull_settings_safe(self) -> PullSettings:
    try:
      ensure_defaults(overwrite=False)
      cfg = read_json(_CONFIG_JSON, required=True)

      # New unified naming: "filters"
      # Back-compat: accept legacy "pull".
      p = cfg.get("filters", {}) if isinstance(cfg, dict) else {}
      if not p:
        p = cfg.get("pull", {}) if isinstance(cfg, dict) else {}
    except Exception:
      p = {}

    allowed_roots = [s for s in p.get("allowed_roots", []) if isinstance(s, str)]
    disallowed_roots = [s for s in p.get("disallowed_roots", []) if isinstance(s, str)]
    return PullSettings(allowed_roots=allowed_roots, disallowed_roots=disallowed_roots)

  def _save_refresh_settings(self) -> None:
    # Kept for compatibility with existing button hooks; now writes config.json.
    self._save_config_now(reason="manual-save-refresh")

  def _save_pull_settings(self) -> None:
    # Kept for compatibility with existing button hooks; now writes config.json.
    self._save_config_now(reason="manual-save-pull")

  # ---------------------------------------------------------------------------
  # UI
  # ---------------------------------------------------------------------------

  def _autosize_ctk_button(self, btn: ctk.CTkButton, *, extra_px: int = 34, min_px: int = 140, max_px: int = 900) -> None:
    """
    Auto-size a CTkButton to fit its current text.
    CustomTkinter doesn't auto-fit width; we measure text and set width in pixels.
    """
    try:
      text = btn.cget("text") or ""
      font = btn.cget("font")
      f = tkfont.Font(font=font)
      w = f.measure(text) + extra_px
      w = max(min_px, min(max_px, w))
      btn.configure(width=w)
    except Exception:
      # If anything fails, leave default width alone.
      pass

  def _build_ui(self) -> None:
    self.grid_columnconfigure(0, weight=1)
    self.grid_rowconfigure(0, weight=1)

    self.tabs = ctk.CTkTabview(self)
    self.tabs.grid(row=0, column=0, sticky="nsew", padx=12, pady=12)

    self.tab_run = self.tabs.add("Run")
    self.tab_config = self.tabs.add("Config")
    self.tab_log = self.tabs.add("Log")

    self._build_run_tab()
    self._build_config_tab()
    self._build_log_tab()

  def _build_run_tab(self) -> None:
    self.tab_run.grid_columnconfigure(0, weight=1)
    self.tab_run.grid_rowconfigure(1, weight=1)

    top = ctk.CTkFrame(self.tab_run)

    top.grid(row=0, column=0, sticky="ew", padx=10, pady=(10, 8))
    top.grid_columnconfigure(6, weight=1)

    self.btn_refresh = ctk.CTkButton(top, text="🔍 Refresh (Scan + Write List)", command=self._on_refresh_clicked)
    self.btn_refresh.grid(row=0, column=0, padx=8, pady=10)

    self.btn_pull = ctk.CTkButton(top, text="⬇️ Pull All (git pull --ff-only)", command=self._on_pull_clicked)
    self.btn_pull.grid(row=0, column=1, padx=8, pady=10)

    self.btn_pull_selected = ctk.CTkButton(top, text="⬇️ Pull Selected", command=self._on_pull_selected_clicked)
    self.btn_pull_selected.grid(row=0, column=2, padx=8, pady=10)

    self.btn_open_selected = ctk.CTkButton(top, text="📂 Open Selected", command=self._on_open_selected_clicked)
    self.btn_open_selected.grid(row=0, column=3, padx=8, pady=10)

    self.btn_stop = ctk.CTkButton(top, text="🛑 Stop", command=self._on_stop_clicked, state="disabled")
    self.btn_stop.grid(row=0, column=4, padx=8, pady=10)

    # Auto-size after layout/font scaling is settled
    self.after(0, lambda: self._autosize_ctk_button(self.btn_refresh))
    self.after(0, lambda: self._autosize_ctk_button(self.btn_pull))
    self.after(0, lambda: self._autosize_ctk_button(self.btn_pull_selected))
    self.after(0, lambda: self._autosize_ctk_button(self.btn_open_selected))
    self.after(0, lambda: self._autosize_ctk_button(self.btn_stop))

    self.var_dry_run = tk.BooleanVar(value=False)
    self.chk_dry_run = ctk.CTkCheckBox(top, text="🧪 Dry Run", variable=self.var_dry_run)
    self.chk_dry_run.grid(row=0, column=5, padx=8, pady=10)

    mid = ctk.CTkFrame(self.tab_run)

    mid.grid(row=1, column=0, sticky="nsew", padx=10, pady=(0, 10))
    mid.grid_columnconfigure(0, weight=1)
    mid.grid_rowconfigure(0, weight=0)  # status/progress
    mid.grid_rowconfigure(1, weight=1)  # table fills remaining height

    # Status + progress (above table)
    status_bar = ctk.CTkFrame(mid)
    status_bar.grid(row=0, column=0, sticky="ew", padx=10, pady=(10, 6))
    status_bar.grid_columnconfigure(1, weight=1)

    self.lbl_status = ctk.CTkLabel(status_bar, text="Idle")
    self.lbl_status.grid(row=0, column=0, padx=(10, 8), pady=8, sticky="w")

    self.progress = ctk.CTkProgressBar(status_bar)
    self.progress.set(0.0)
    self.progress.grid(row=0, column=1, padx=(0, 10), pady=8, sticky="ew")

    # Repo table (ttk Treeview)
    repos_frame = ctk.CTkFrame(mid)
    repos_frame.grid(row=1, column=0, sticky="nsew", padx=10, pady=(0, 10))

    repos_frame.grid_columnconfigure(0, weight=1)
    repos_frame.grid_rowconfigure(0, weight=1)

    self.tree = ttk.Treeview(
      repos_frame,
      columns=("idx", "repo", "key", "seen", "pulled", "status"),
      show="headings",
      height=1,  # let the frame decide height
      style="Treeview",
    )

    # Column headers
    self.tree.heading("idx", text="#", anchor="center")
    self.tree.heading("repo", text="Repository", anchor="w")
    self.tree.heading("key", text="SSH Key", anchor="w")
    self.tree.heading("seen", text="Last Seen", anchor="center")
    self.tree.heading("pulled", text="Last Pull", anchor="center")
    self.tree.heading("status", text="Status", anchor="center")

    # Column cells
    self.tree.column("idx", width=56, minwidth=44, anchor="center", stretch=False)
    self.tree.column("repo", width=460, minwidth=180, anchor="w", stretch=True)
    self.tree.column("key", width=320, minwidth=140, anchor="w", stretch=True)
    self.tree.column("seen", width=160, minwidth=140, anchor="center", stretch=False)
    self.tree.column("pulled", width=160, minwidth=140, anchor="center", stretch=False)
    self.tree.column("status", width=220, minwidth=180, anchor="center", stretch=False)

    # Row coloring:
    # - Grey: idle/queued
    # - Green: done/updated
    # - Yellow: bare repo
    # - Red: error
    # - Blue: in-progress pulling/syncing.
    self.tree.tag_configure("odd", background=_ctk_color(ctk.ThemeManager.theme["CTkFrame"]["fg_color"]))
    self.tree.tag_configure("even", background=_ctk_color(ctk.ThemeManager.theme["CTkFrame"]["top_fg_color"]))

    # Grey (idle/queued)
    self.tree.tag_configure("status_idle_even", background=_ctk_color(ctk.ThemeManager.theme["CTkFrame"]["fg_color"]))
    self.tree.tag_configure("status_idle_odd", background=_ctk_color(ctk.ThemeManager.theme["CTkFrame"]["top_fg_color"]))

    # Green (done/updated)
    self.tree.tag_configure("status_done_even", background="#1f3d2b")
    self.tree.tag_configure("status_done_odd", background="#244632")

    # Blue (in-progress pull)
    self.tree.tag_configure("status_pulling_even", background="#1f2f3d")
    self.tree.tag_configure("status_pulling_odd", background="#243746")

    # Red (error)
    self.tree.tag_configure("status_error_even", background="#4b1f1f")
    self.tree.tag_configure("status_error_odd", background="#401a1a")

    # Warning / skipped (yellow) — bare repo or unborn HEAD
    self.tree.tag_configure("status_warn_even", background="#3d3320")
    self.tree.tag_configure("status_warn_odd", background="#463a24")

    ysb = ttk.Scrollbar(
      repos_frame,
      orient="vertical",
      command=self.tree.yview,
      style="Dark.Vertical.TScrollbar",
    )

    xsb = ttk.Scrollbar(
      repos_frame,
      orient="horizontal",
      command=self.tree.xview,
      style="Dark.Horizontal.TScrollbar",
    )

    self.tree.configure(yscroll=ysb.set, xscroll=xsb.set)
    self.tree.grid(row=0, column=0, sticky="nsew")

    ysb.grid(row=0, column=1, sticky="ns")
    xsb.grid(row=1, column=0, sticky="ew")

    self._install_treeview_context_menu(self.tree)
    self._install_treeview_cell_tooltip(self.tree)
    self._install_treeview_fit_columns(self.tree, repos_frame)

    # Selection-dependent buttons (gold standard UX)
    self.tree.bind("<<TreeviewSelect>>", lambda _e: self._update_selection_dependent_controls())
    self._update_selection_dependent_controls()

  def _build_log_tab(self) -> None:
    self.tab_log.grid_columnconfigure(0, weight=1)
    self.tab_log.grid_rowconfigure(0, weight=1)

    root = ctk.CTkFrame(self.tab_log)
    root.grid(row=0, column=0, sticky="nsew", padx=10, pady=10)
    root.grid_columnconfigure(0, weight=1)
    root.grid_rowconfigure(1, weight=1)

    top = ctk.CTkFrame(root)
    top.grid(row=0, column=0, sticky="ew", padx=10, pady=(10, 6))
    top.grid_columnconfigure(0, weight=1)

    ctk.CTkLabel(top, text="Log").grid(row=0, column=0, padx=6, pady=6, sticky="w")

    self.btn_clear_log = ctk.CTkButton(top, text="Clear", width=90, command=self._clear_log)
    self.btn_clear_log.grid(row=0, column=1, padx=6, pady=6)

    self.txt_log = ctk.CTkTextbox(root, wrap="none", font=self._font_textbox)
    self.txt_log.grid(row=1, column=0, sticky="nsew", padx=10, pady=(0, 10))


  def _build_config_tab(self) -> None:
    self.tab_config.grid_columnconfigure(0, weight=1)
    self.tab_config.grid_rowconfigure(0, weight=1)
    self.tab_config.grid_rowconfigure(1, weight=0)

    root = ctk.CTkFrame(self.tab_config)
    root.grid(row=0, column=0, sticky="nsew", padx=10, pady=10)
    root.grid_columnconfigure(0, weight=1)
    root.grid_rowconfigure(0, weight=1)
    root.grid_rowconfigure(1, weight=0)

    # ----------------------------------------------------------------------------
    # Scan / Manifest (used by Refresh)
    # ----------------------------------------------------------------------------
    scan = ctk.CTkFrame(root)
    scan.grid(row=0, column=0, sticky="nsew", padx=10, pady=(10, 6))
    scan.grid_columnconfigure(0, weight=1)
    scan.grid_rowconfigure(7, weight=1)  # ignore_prefixes textbox expands

    ctk.CTkLabel(scan, text="Scan + Manifest (used by Refresh)").grid(row=0, column=0, padx=10, pady=(10, 6), sticky="w")

    # scan_roots listbox
    ctk.CTkLabel(scan, text="scan_roots").grid(row=1, column=0, padx=10, pady=(6, 2), sticky="w")

    self.lb_scan_roots = tk.Listbox(scan, height=6, font=("Segoe UI", _UI_FONT_LISTBOX))
    self.lb_scan_roots.grid(row=2, column=0, padx=10, pady=(0, 6), sticky="ew")
    self._style_listbox(self.lb_scan_roots)

    scan_btns = ctk.CTkFrame(scan)
    scan_btns.grid(row=3, column=0, padx=10, pady=(0, 10), sticky="ew")
    scan_btns.grid_columnconfigure(3, weight=1)

    ctk.CTkButton(scan_btns, text="Add Folder…", command=lambda: self._lb_add_folder(self.lb_scan_roots)).grid(row=0, column=0, padx=6, pady=6)
    ctk.CTkButton(scan_btns, text="Add Text…", command=lambda: self._lb_add_text(self.lb_scan_roots, "Add scan root")).grid(row=0, column=1, padx=6, pady=6)
    ctk.CTkButton(scan_btns, text="Remove", command=lambda: self._lb_remove_selected(self.lb_scan_roots)).grid(row=0, column=2, padx=6, pady=6)

    # default_ssh_key
    ctk.CTkLabel(
      scan,
      text="default_ssh_key (valid: private PuTTY .ppk; invalid: public .pub key)",
    ).grid(row=4, column=0, padx=10, pady=(6, 2), sticky="w")
    key_row = ctk.CTkFrame(scan)
    key_row.grid(row=5, column=0, padx=10, pady=(0, 10), sticky="ew")
    key_row.grid_columnconfigure(0, weight=1)

    self.ent_default_key = ctk.CTkEntry(key_row, font=self._font_entry)
    self.ent_default_key.grid(row=0, column=0, padx=(0, 8), pady=6, sticky="ew")
    ctk.CTkButton(key_row, text="Browse…", width=110, command=self._browse_key).grid(row=0, column=1, padx=(0, 0), pady=6)

    self.ent_default_key.bind("<KeyRelease>", lambda _e: self._autosave_debounced())
    self.ent_default_key.bind("<FocusOut>", lambda _e: self._autosave_debounced())

    # ignore_prefixes textbox
    ctk.CTkLabel(scan, text="ignore_prefixes (one per line)").grid(row=6, column=0, padx=10, pady=(6, 2), sticky="w")
    self.txt_ignore = ctk.CTkTextbox(scan, height=110, font=self._font_textbox)
    self.txt_ignore.grid(row=7, column=0, padx=10, pady=(0, 10), sticky="nsew")

    self.txt_ignore.bind("<KeyRelease>", lambda _e: self._autosave_debounced())
    self.txt_ignore.bind("<FocusOut>", lambda _e: self._autosave_debounced())

    # output (hard-coded)
    ctk.CTkLabel(scan, text="output (hard-coded)").grid(row=8, column=0, padx=10, pady=(6, 2), sticky="w")
    self.lbl_manifest_path = ctk.CTkLabel(scan, text=path_safe(_REPOSITORY_MANIFEST_JSON))
    self.lbl_manifest_path.grid(row=9, column=0, padx=10, pady=(0, 10), sticky="w")

    # ----------------------------------------------------------------------------
    # Filters (apply to BOTH Refresh (manifest creation) and Pull)
    # ----------------------------------------------------------------------------
    filters = ctk.CTkFrame(root)
    filters.grid(row=1, column=0, sticky="ew", padx=10, pady=(6, 10))
    filters.grid_columnconfigure(0, weight=1)
    filters.grid_columnconfigure(1, weight=1)

    ctk.CTkLabel(filters, text="Filters (apply to Refresh + Pull)").grid(row=0, column=0, columnspan=2, padx=10, pady=(10, 6), sticky="w")

    # allowed_roots (left)
    ctk.CTkLabel(filters, text="allowed_roots").grid(row=1, column=0, padx=10, pady=(6, 2), sticky="w")

    self.lb_allowed_roots = tk.Listbox(filters, height=6, font=("Segoe UI", _UI_FONT_LISTBOX))
    self.lb_allowed_roots.grid(row=2, column=0, padx=10, pady=(0, 6), sticky="ew")
    self._style_listbox(self.lb_allowed_roots)

    allow_btns = ctk.CTkFrame(filters)
    allow_btns.grid(row=3, column=0, padx=10, pady=(0, 10), sticky="ew")
    allow_btns.grid_columnconfigure(3, weight=1)

    ctk.CTkButton(allow_btns, text="Add Folder…", command=lambda: self._lb_add_folder(self.lb_allowed_roots)).grid(row=0, column=0, padx=6, pady=6)
    ctk.CTkButton(allow_btns, text="Add Text…", command=lambda: self._lb_add_text(self.lb_allowed_roots, "Add allowed root")).grid(row=0, column=1, padx=6, pady=6)
    ctk.CTkButton(allow_btns, text="Remove", command=lambda: self._lb_remove_selected(self.lb_allowed_roots)).grid(row=0, column=2, padx=6, pady=6)

    # disallowed_roots (right)
    ctk.CTkLabel(filters, text="disallowed_roots").grid(row=1, column=1, padx=10, pady=(6, 2), sticky="w")

    self.lb_disallowed_roots = tk.Listbox(filters, height=6, font=("Segoe UI", _UI_FONT_LISTBOX))
    self.lb_disallowed_roots.grid(row=2, column=1, padx=10, pady=(0, 6), sticky="ew")
    self._style_listbox(self.lb_disallowed_roots)

    deny_btns = ctk.CTkFrame(filters)
    deny_btns.grid(row=3, column=1, padx=10, pady=(0, 10), sticky="ew")
    deny_btns.grid_columnconfigure(3, weight=1)

    ctk.CTkButton(deny_btns, text="Add Folder…", command=lambda: self._lb_add_folder(self.lb_disallowed_roots)).grid(row=0, column=0, padx=6, pady=6)
    ctk.CTkButton(deny_btns, text="Add Text…", command=lambda: self._lb_add_text(self.lb_disallowed_roots, "Add disallowed root")).grid(row=0, column=1, padx=6, pady=6)
    ctk.CTkButton(deny_btns, text="Remove", command=lambda: self._lb_remove_selected(self.lb_disallowed_roots)).grid(row=0, column=2, padx=6, pady=6)

    # ----------------------------------------------------------------------------
    # Bottom actions
    # ----------------------------------------------------------------------------
    bottom = ctk.CTkFrame(self.tab_config)
    bottom.grid(row=1, column=0, sticky="ew", padx=10, pady=(0, 10))
    bottom.grid_columnconfigure(6, weight=1)

    # Restore (disabled/grey if missing)
    self.btn_restore_config = ctk.CTkButton(bottom, text="🧯 Restore config.json", command=self._restore_config_clicked, state="disabled")
    self.btn_restore_config.grid(row=0, column=0, padx=8, pady=10)

    ctk.CTkButton(bottom, text="🔄 Reload From Disk", command=self._reload_settings_from_disk).grid(row=0, column=1, padx=8, pady=10)
    ctk.CTkButton(bottom, text="🧩 Bootstrap Defaults (non-destructive)", command=self._bootstrap_defaults_clicked).grid(row=0, column=2, padx=8, pady=10)
    ctk.CTkButton(bottom, text="📂 Open script folder", command=self._open_config_folder).grid(row=0, column=3, padx=8, pady=10)

    self._sync_settings_to_ui()
    self._ui_update_restore_button_state()

  # ---------------------------------------------------------------------------
  # UI helpers
  # ---------------------------------------------------------------------------

  def _ctk_theme_color(self, widget_key: str, prop: str, *, fallback: str) -> str:
    """
    Get a color from the active CustomTkinter theme.

    CustomTkinter theme entries frequently look like:
      ctk.ThemeManager.theme["CTkFrame"]["fg_color"] == ["#light", "#dark"]

    We pick based on current appearance mode.
    """
    try:
      mode = ctk.get_appearance_mode()  # "Dark" or "Light"
      t = (ctk.ThemeManager.theme or {}).get(widget_key, {})
      v = t.get(prop)

      if isinstance(v, (list, tuple)) and len(v) >= 2:
        return v[0] if mode == "Light" else v[1]
      if isinstance(v, str) and v:
        return v
    except Exception:
      pass

    return fallback

  def _apply_ttk_theme(self) -> None:
    """
    Make ttk widgets (Treeview/Scrollbar/etc.) match the CustomTkinter theme.
    """
    try:
      style = ttk.Style(self)

      # "clam" is the most consistent for custom coloring across platforms.
      try:
        style.theme_use("clam")
      except Exception:
        pass

      # Pull colors from CTk theme (with safe fallbacks)
      bg = self._ctk_theme_color("CTkFrame", "fg_color", fallback="#1f1f1f")
      fg = self._ctk_theme_color("CTkLabel", "text_color", fallback="#e6e6e6")
      entry_bg = self._ctk_theme_color("CTkEntry", "fg_color", fallback="#2b2b2b")
      border = self._ctk_theme_color("CTkEntry", "border_color", fallback="#3a3a3a")
      accent = self._ctk_theme_color("CTkButton", "fg_color", fallback="#2a6df4")
      hover = self._ctk_theme_color("CTkButton", "hover_color", fallback="#1f5fe0")

      # Treeview
      style.configure(
        "Ctk.Treeview",
        background=entry_bg,
        fieldbackground=entry_bg,
        foreground=fg,
        bordercolor=border,
        lightcolor=border,
        darkcolor=border,
        rowheight=26,
      )
      style.map(
        "Ctk.Treeview",
        background=[("selected", accent)],
        foreground=[("selected", "#ffffff")],
      )

      # Treeview headings
      style.configure(
        "Ctk.Treeview.Heading",
        background=bg,
        foreground=fg,
        relief="flat",
      )
      style.map(
        "Ctk.Treeview.Heading",
        background=[("active", hover)],
        foreground=[("active", "#ffffff")],
      )

      # Scrollbars (vertical + horizontal)
      style.configure(
        "Ctk.Vertical.TScrollbar",
        troughcolor=bg,
        background=entry_bg,
        bordercolor=border,
        arrowcolor=fg,
        relief="flat",
      )
      style.configure(
        "Ctk.Horizontal.TScrollbar",
        troughcolor=bg,
        background=entry_bg,
        bordercolor=border,
        arrowcolor=fg,
        relief="flat",
      )
    except Exception:
      # If anything about ttk theming fails on a platform/theme, fail soft.
      pass

  def _style_listbox(self, lb: tk.Listbox) -> None:
    """Make a tk.Listbox look like the current CustomTkinter theme."""
    try:
      bg = _ctk_color(ctk.ThemeManager.theme["CTkFrame"]["fg_color"])
      fg = _ctk_color(ctk.ThemeManager.theme["CTkLabel"]["text_color"])
      sel_bg = _ctk_color(ctk.ThemeManager.theme["CTkButton"]["hover_color"])
      # selection foreground stays readable (same as fg in CTk)
      lb.configure(
        bg=bg,
        fg=fg,
        selectbackground=sel_bg,
        selectforeground=fg,
        relief="flat",
        borderwidth=0,
        highlightthickness=1,
        highlightbackground=bg,
        highlightcolor=bg,
        activestyle="none",
      )
    except Exception:
      pass

  def _sync_settings_to_ui(self) -> None:
    self._ui_set_listbox(self.lb_scan_roots, self.refresh_settings.scan_roots)
    self._ui_set_listbox(self.lb_allowed_roots, self.pull_settings.allowed_roots)
    self._ui_set_listbox(self.lb_disallowed_roots, self.pull_settings.disallowed_roots)

    self.ent_default_key.delete(0, "end")
    self.ent_default_key.insert(0, self.refresh_settings.default_ssh_key)

    self.txt_ignore.delete("1.0", "end")
    self.txt_ignore.insert("1.0", "\n".join(self.refresh_settings.ignore_prefixes))

    if hasattr(self, "lbl_manifest_path"):
      try:
        self.lbl_manifest_path.configure(text=path_safe(_REPOSITORY_MANIFEST_JSON))
      except Exception:
        pass

    self._ui_update_restore_button_state()

  def _ui_set_listbox(self, lb: tk.Listbox, items: List[str]) -> None:
    lb.delete(0, "end")
    for it in items:
      if it is None:
        continue
      lb.insert("end", str(it))

  def _ui_get_listbox_items(self, lb: tk.Listbox) -> List[str]:
    return [lb.get(i) for i in range(lb.size())]

  def _ui_get_ignore_prefixes(self) -> List[str]:
    raw = self.txt_ignore.get("1.0", "end").splitlines()
    out = []
    for line in raw:
      s = line.strip()
      if not s:
        continue
      out.append(s)
    return out or ["$"]

  def _lb_add_folder(self, lb: tk.Listbox) -> None:
    d = filedialog.askdirectory(initialdir=_SCRIPT_DIR)
    if not d:
      return
    lb.insert("end", d)
    self._save_config_now(reason="folder-added")

  def _lb_add_text(self, lb: tk.Listbox, title: str) -> None:
    dialog = ctk.CTkInputDialog(text="Enter a path (absolute or relative to script):", title=title)
    v = (dialog.get_input() or "").strip()
    if not v:
      return
    lb.insert("end", v)
    self._save_config_now(reason="path-added")

  def _lb_remove_selected(self, lb: tk.Listbox) -> None:
    sel = list(lb.curselection())
    sel.reverse()
    for idx in sel:
      lb.delete(idx)
    self._save_config_now(reason="path-removed")

  def _browse_key(self) -> None:
    p = filedialog.askopenfilename(initialdir=_SCRIPT_DIR, title="Select SSH key file (PuTTY .ppk or key path)")
    if not p:
      return
    self.ent_default_key.delete(0, "end")
    self.ent_default_key.insert(0, p)
    self._save_config_now(reason="ssh-key-selected")

  def _open_config_folder(self) -> None:
    try:
      if os.name == "nt":
        os.startfile(_SCRIPT_DIR)  # type: ignore
      else:
        subprocess.run(["xdg-open", _SCRIPT_DIR], check=False)
    except Exception as e:
      messagebox.showerror("Error", f"Could not open script folder:\n{e}")

  # ---------------------------------------------------------------------------
  # Logging + queue pump
  # ---------------------------------------------------------------------------

  def _log(self, level: str, msg: str) -> None:
    self._log_q.put((level, msg))

  def _clear_log(self) -> None:
    self.txt_log.delete("1.0", "end")

  def _pump_queues(self) -> None:
    # Pump log lines
    while True:
      try:
        level, msg = self._log_q.get_nowait()
      except queue.Empty:
        break
      ts = time.strftime("%H:%M:%S")
      line = f"[{ts}] {msg}\n"
      self.txt_log.insert("end", line)
      self.txt_log.see("end")

    # Pump UI actions
    while True:
      try:
        kind, payload = self._ui_q.get_nowait()
      except queue.Empty:
        break

      if kind == "status":
        self.lbl_status.configure(text=str(payload))
      elif kind == "progress":
        try:
          self.progress.set(float(payload))
        except Exception:
          pass
      elif kind == "tree_clear":
        for iid in self.tree.get_children():
          self.tree.delete(iid)
      elif kind == "tree_add":
        # payload: (repo, key, status, last_seen, last_pull)
        repo, key, status, last_seen, last_pull = payload
        self._tree_add_row(repo, key, status, last_seen=last_seen, last_pull=last_pull)

      elif kind == "tree_update_by_repo":
        # payload: (repo, key, status, last_seen, last_pull)
        repo, key, status, last_seen, last_pull = payload
        self._tree_update(repo, key, status, last_seen=last_seen, last_pull=last_pull)

    self.after(80, self._pump_queues)

  def _tree_add_row(
    self,
    repo: str,
    key: str,
    status: str,
    *,
    idx: Optional[int] = None,
    last_seen: str = "—",
    last_pull: str = "—",
  ) -> None:
    next_idx = idx if (idx is not None) else (len(self.tree.get_children()) + 1)
    zebra = "even" if ((next_idx) % 2 == 0) else "odd"
    tags = (self._tree_compose_row_tag(status, zebra),)
    self.tree.insert("", "end", values=(str(next_idx), repo, key, last_seen, last_pull, status), tags=tags)

  def _tree_update(
    self,
    repo: str,
    key: str,
    status: str,
    *,
    last_seen: Optional[str] = None,
    last_pull: Optional[str] = None,
  ) -> None:
    # Find row by repo (repo is column #2 -> index 1)
    for iid in self.tree.get_children():
      vals = self.tree.item(iid, "values")
      if vals and len(vals) >= 6 and vals[1] == repo:
        zebra = self._tree_zebra_from_existing_row(iid)
        tags = (self._tree_compose_row_tag(status, zebra),)

        row_idx = vals[0]
        seen = last_seen if (last_seen is not None) else (vals[3] if len(vals) >= 4 else "—")
        pulled = last_pull if (last_pull is not None) else (vals[4] if len(vals) >= 5 else "—")

        self.tree.item(iid, values=(row_idx, repo, key, seen, pulled, status), tags=tags)
        return

    # If missing, append as a new row
    self._tree_add_row(repo, key, status, last_seen=(last_seen or "—"), last_pull=(last_pull or "—"))

  def _tree_status_tag_base(self, status: str) -> Optional[str]:
    s = (status or "").strip().lower()
    if not s:
      return None

    # Warning (non-error) - should be YELLOW
    if "bare" in s or "unborn" in s or "no commits" in s:
      return "status_warn"

    # Error - should be RED
    if "error" in s or "fail" in s:
      return "status_error"

    # Success / Done - should be GREEN
    if "updated" in s or "done" in s or "success" in s or "no changes" in s:
      return "status_done"

    # Idle / queued / found / dry-run - should be GREY
    if "idle" in s or "queued" in s or "dry run" in s or "found" in s:
      return "status_idle"

    # In-progress (BLUE) — this is specifically a git pull in this tool.
    if (
      "pull" in s
      or "pulling" in s
      or "sync" in s
      or "fetch" in s
      or "update" in s
      or "clon" in s
      or "clone" in s
    ):
      return "status_pulling"

    return None

  def _tree_zebra_from_existing_row(self, iid: str) -> str:
    tags = self.tree.item(iid, "tags") or ()
    for t in tags:
      if t.endswith("_even") or t == "even":
        return "even"
      if t.endswith("_odd") or t == "odd":
        return "odd"

    # Fallback: derive from current order
    children = list(self.tree.get_children())
    try:
      idx = children.index(iid) + 1
    except ValueError:
      idx = len(children) + 1
    return "even" if (idx % 2 == 0) else "odd"

  def _tree_compose_row_tag(self, status: str, zebra: str) -> str:
    base = self._tree_status_tag_base(status)
    return f"{base}_{zebra}" if base else zebra

  # ---------------------------------------------------------------------------
  # Worker management
  # ---------------------------------------------------------------------------

  def _set_running(self, running: bool) -> None:
    if running:
      self.btn_refresh.configure(state="disabled")
      self.btn_pull.configure(state="disabled")
      if hasattr(self, "btn_pull_selected"):
        self.btn_pull_selected.configure(state="disabled")
      if hasattr(self, "btn_open_selected"):
        self.btn_open_selected.configure(state="disabled")
      if hasattr(self, "btn_stop"):
        self.btn_stop.configure(state="normal")
    else:
      self.btn_refresh.configure(state="normal")
      self.btn_pull.configure(state="normal")
      if hasattr(self, "btn_pull_selected"):
        self.btn_pull_selected.configure(state="normal")
      if hasattr(self, "btn_open_selected"):
        self.btn_open_selected.configure(state="normal")
      if hasattr(self, "btn_stop"):
        self.btn_stop.configure(state="disabled")

  def _run_worker(self, fn) -> None:
    if self._worker and self._worker.is_alive():
      messagebox.showwarning("Busy", "An operation is already running.")
      return

    self._worker_stop.clear()
    self._set_running(True)

    def _wrap():
      try:
        fn()
      except Exception as e:
        self._log("fail", f"❌ Unhandled error: {e}")
      finally:
        self._pull_only_paths = None
        self._ui_q.put(("progress", 0.0))
        self._ui_q.put(("status", "Idle"))
        self._set_running(False)

    self._worker = threading.Thread(target=_wrap, daemon=True)
    self._worker.start()

  # ---------------------------------------------------------------------------
  # Button handlers
  # ---------------------------------------------------------------------------

  def _bootstrap_defaults_clicked(self) -> None:
    try:
      ensure_defaults(overwrite=False)
      self._log("ok", "✅ Bootstrapped config.json (if missing).")
      self._reload_settings_from_disk()
    except Exception as e:
      messagebox.showerror("Bootstrap failed", str(e))

  def _on_refresh_clicked(self) -> None:
    self._run_worker(self._do_refresh)

  def _on_pull_clicked(self) -> None:
    self._pull_only_paths = None
    self._run_worker(self._do_pull)

  def _on_pull_selected_clicked(self) -> None:
    paths = self._get_selected_repo_paths()
    if not paths:
      messagebox.showwarning("No selection", "Select one or more repositories in the table first.")
      return

    self._pull_only_paths = set(paths)
    self._run_worker(self._do_pull)

  def _on_open_selected_clicked(self) -> None:
    paths = self._get_selected_repo_paths()
    if not paths:
      messagebox.showwarning("No selection", "Select one or more repositories in the table first.")
      return
    self._open_paths(paths)

  def _get_selected_repo_paths(self) -> List[str]:
    """
    Returns selected repo paths from the treeview (Repository column).
    """
    out: List[str] = []
    for iid in (self.tree.selection() or ()):
      vals = self.tree.item(iid, "values") or ()
      if len(vals) >= 2:
        p = str(vals[1] or "").strip()
        if p:
          out.append(p)
    return out

  def _get_selected_repo_keys(self) -> List[str]:
    """
    Returns selected SSH key paths from the treeview (SSH Key column).
    """
    out: List[str] = []
    for iid in (self.tree.selection() or ()):
      vals = self.tree.item(iid, "values") or ()
      if len(vals) >= 3:
        k = str(vals[2] or "").strip()
        if k:
          out.append(k)
    return out

  def _copy_to_clipboard(self, text: str) -> None:
    try:
      self.clipboard_clear()
      self.clipboard_append(text)
      self.update_idletasks()
      self._log("ok", "📋 Copied to clipboard.")
    except Exception as e:
      self._log("warn", f"⚠️  Clipboard copy failed: {e}")

  def _open_paths(self, paths: List[str]) -> None:
    for p in paths:
      try:
        if os.name == "nt":
          os.startfile(p)  # type: ignore
        else:
          subprocess.run(["xdg-open", p], check=False)
      except Exception as e:
        self._log("warn", f"⚠️  Could not open: {p} ({e})")

  def _on_stop_clicked(self) -> None:
    """
    SAFE STOP:
    - Sets the stop event.
    - Worker checks it between roots / between repos.
    """
    if self._worker and self._worker.is_alive():
      self._log("warn", "🛑 Stop requested (will finish current unit of work).")
      self._ui_q.put(("status", "Stopping..."))
      self._worker_stop.set()

  # ---------------------------------------------------------------------------
  # Operations
  # ---------------------------------------------------------------------------

  def _save_config_now(self, *, reason: str) -> None:
    """
    Write config.json from current UI state.
    Creates config_restore.json ONCE before the first auto-write so it can be restored.

    Unified config layout:
      - scan: settings used for scanning roots + producing the manifest
      - filters: prefix filters applied by BOTH refresh (manifest creation) and pull
    """
    try:
      self._ensure_restore_snapshot()

      scan_cfg = {
        "scan_roots": self._ui_get_listbox_items(self.lb_scan_roots),
        "ignore_prefixes": self._ui_get_ignore_prefixes(),
        "default_ssh_key": self.ent_default_key.get().strip(),
      }

      filters_cfg = {
        "allowed_roots": self._ui_get_listbox_items(self.lb_allowed_roots),
        "disallowed_roots": self._ui_get_listbox_items(self.lb_disallowed_roots),
      }

      cfg = {
        "scan": scan_cfg,
        "filters": filters_cfg,
      }

      write_json(_CONFIG_JSON, cfg, indent=2)
      self._ui_update_restore_button_state()
      self._log("info", f"💾 Auto-saved config.json ({reason})")
    except Exception as e:
      self._log("warn", f"⚠️  Auto-save failed: {e}")

  def _autosave_debounced(self) -> None:
    """
    Debounced auto-save for typing-heavy widgets.
    """
    try:
      job = getattr(self, "_autosave_job", None)
      if job is not None:
        try:
          self.after_cancel(job)
        except Exception:
          pass
      self._autosave_job = self.after(350, lambda: self._save_config_now(reason="debounced"))
    except Exception:
      pass

  def _ensure_restore_snapshot(self) -> None:
    """
    Create config_restore.json ONCE before first write to config.json.
    """
    if os.path.exists(_CONFIG_RESTORE_JSON):
      return

    # Snapshot what currently exists (config.json if present else default)
    src = _CONFIG_JSON if os.path.exists(_CONFIG_JSON) else _CONFIG_DEFAULT_JSON
    try:
      shutil.copy2(src, _CONFIG_RESTORE_JSON)
      self._log("ok", f"🧯 Created restore snapshot: {path_safe(_CONFIG_RESTORE_JSON)}")
    except Exception as e:
      self._log("warn", f"⚠️  Could not create restore snapshot: {e}")

  def _ui_update_restore_button_state(self) -> None:
    """
    Enable/disable Restore button based on presence of config_restore.json.
    """
    try:
      has_restore = os.path.exists(_CONFIG_RESTORE_JSON)
      if hasattr(self, "btn_restore_config"):
        self.btn_restore_config.configure(state=("normal" if has_restore else "disabled"))
    except Exception:
      pass

  def _restore_config_clicked(self) -> None:
    """
    Restore config.json from config_restore.json then reload UI.
    """
    try:
      if not os.path.exists(_CONFIG_RESTORE_JSON):
        self._log("warn", "⚠️  No config_restore.json present; nothing to restore.")
        self._ui_update_restore_button_state()
        return

      shutil.copy2(_CONFIG_RESTORE_JSON, _CONFIG_JSON)
      self._log("ok", f"🧯 Restored config.json from {path_safe(_CONFIG_RESTORE_JSON)}")
      self._reload_settings_from_disk()
    except Exception as e:
      messagebox.showerror("Restore failed", str(e))

  def _do_refresh(self) -> None:
    self._ui_q.put(("status", "Refreshing…"))

    preflight("refresh")
    cfg = read_json(_CONFIG_JSON, required=True)

    # Unified config: scan + filters (back-compat to refresh + pull)
    scan_cfg = cfg.get("scan", {}) if isinstance(cfg, dict) else {}
    if not scan_cfg:
      scan_cfg = cfg.get("refresh", {}) if isinstance(cfg, dict) else {}

    filters_cfg = cfg.get("filters", {}) if isinstance(cfg, dict) else {}
    if not filters_cfg:
      filters_cfg = cfg.get("pull", {}) if isinstance(cfg, dict) else {}

    scan_roots = scan_cfg.get("scan_roots", [])
    ignore_prefixes = scan_cfg.get("ignore_prefixes", ["$"])
    default_ssh_key = scan_cfg.get("default_ssh_key", "")

    scan_roots = [s for s in scan_roots if isinstance(s, str)]
    ignore_prefixes = [s for s in ignore_prefixes if isinstance(s, str)]

    allowed_prefixes = [path_safe(p) for p in filters_cfg.get("allowed_roots", []) if isinstance(p, str)]
    disallowed_prefixes = [path_safe(p) for p in filters_cfg.get("disallowed_roots", []) if isinstance(p, str)]

    def _passes_filters(repo_path: str) -> bool:
      safe_path = path_safe(repo_path)

      if any(safe_path.startswith(disallowed) for disallowed in disallowed_prefixes):
        return False

      if allowed_prefixes and not any(safe_path.startswith(allowed) for allowed in allowed_prefixes):
        return False

      return True

    manifest_json_abs = path_safe(_REPOSITORY_MANIFEST_JSON)
    default_ssh_key_abs = path_safe(default_ssh_key) if default_ssh_key else ""

    self._log("info", "------------------------------------------------------------")
    self._log("info", "BEGIN REFRESH (scan + apply filters + write manifest v2)")
    self._log("info", "------------------------------------------------------------")

    if not scan_roots:
      self._log("warn", "⚠️  scan_roots is empty. Nothing to scan.")
      return

    # Load existing manifest v2 (preserve pulled_at / last_error etc)
    manifest: ManifestV2 = load_manifest_v2(manifest_json_abs)
    byp = repos_by_path(manifest)

    # Reset UI table for fresh scan display
    self._ui_q.put(("tree_clear", None))

    skipped_by_filter = 0
    total_roots = len(scan_roots)

    for i, root in enumerate(scan_roots, start=1):
      if self._worker_stop.is_set():
        self._log("warn", "🛑 Stop requested; ending refresh early (no manifest write).")
        return

      self._ui_q.put(("status", f"Refreshing... ({i} of {total_roots} root{'' if total_roots == 1 else 's'})"))

      root_abs = path_safe(root)
      if not root_abs or not os.path.isdir(root_abs):
        self._log("warn", f"⚠️  Skipping missing scan root: {root_abs}")
        self._ui_q.put(("progress", min(1.0, i / max(1, total_roots))))
        continue

      repo_keys = find_git_repos_with_keys(root_abs, default_ssh_key_abs, ignore_prefixes, self._log)
      for repo_path, key in repo_keys.items():

        repo_path = path_safe(repo_path)
        key = path_safe(key)

        if not _passes_filters(repo_path):
          skipped_by_filter += 1
          continue

        seen = now_iso()

        # Preserve prior state if present
        r = byp.get(repo_path)
        if r is None:
          r = upsert_repo(
            manifest,
            repo_path,
            ssh_key=key,
            phase="idle",
            message="Found",
            seen_at=seen,
          )
          byp[repo_path] = r
        else:
          upsert_repo(
            manifest,
            repo_path,
            ssh_key=key,
            phase=str(r.get("phase", "idle") or "idle"),
            message="Found",
            seen_at=seen,
          )

        # Update in-memory map used by tooltips
        self._repo_state_by_path[repo_path] = byp[repo_path]

        self._ui_q.put(("tree_add", (repo_path, key, "Found", ts_short(seen), ts_short(str(r.get("pulled_at", "") or "")))))

      self._ui_q.put(("progress", min(1.0, i / max(1, total_roots))))

    dry = self.var_dry_run.get()
    if dry:
      self._log("warn", f"🧪 DRY RUN: Would write v2 manifest with {len(manifest.get('repos', []) or [])} repos to: {manifest_json_abs}")
    else:
      save_manifest_v2(manifest_json_abs, manifest, dry_run=False)
      self._log("ok", f"✅ Saved v2 manifest ({len(manifest.get('repos', []) or [])} repos) to {manifest_json_abs}")

    if skipped_by_filter:
      self._log("info", f"ℹ️  Skipped by filters: {skipped_by_filter}")

    self._log("info", "------------------------------------------------------------")
    self._log("ok", "END REFRESH")
    self._log("info", "------------------------------------------------------------")

  def _do_pull(self) -> None:
    self._ui_q.put(("status", "Pulling…"))

    preflight("pull")

    repo_list_path = _REPOSITORY_MANIFEST_JSON
    pull_filters_path = _CONFIG_JSON

    self._log("info", "------------------------------------------------------------")
    self._log("info", "BEGIN PULL (git pull --ff-only)")
    self._log("info", "------------------------------------------------------------")

    try:
      subprocess.run(["git", "--version"], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    except Exception as e:
      self._log("fail", f"❌ git not found or not runnable: {e}")
      return

    manifest, repos = load_repo_manifest_for_pull(repo_list_path, pull_filters_path)
    if not repos:
      self._log("warn", "⚠️  No repositories matched your filters.")
      return

    if self._pull_only_paths:
      only = self._pull_only_paths
      repos = [r for r in repos if path_safe(str(r.get("path", "") or "")) in only]

      if not repos:
        self._log("warn", "⚠️  None of the selected repos matched your current filters.")
        return

      self._log("info", f"🎯 Pull Selected enabled: {len(repos)} repo{'' if len(repos) == 1 else 's'}")

    # Update in-memory state map
    self._repo_state_by_path = repos_by_path(manifest)

    # Keep the full table visible.
    # Only mark TARGET repos as queued (do NOT clear/rebuild the table).
    for r in repos:
      repo_path = path_safe(str(r.get("path", "") or ""))
      ssh_key = path_safe(str(r.get("ssh_key", "") or ""))
      seen = ts_short(str(r.get("seen_at", "") or ""))
      pulled = ts_short(str(r.get("pulled_at", "") or ""))
      self._ui_q.put(("tree_update_by_repo", (repo_path, ssh_key, "Queued", seen, pulled)))

    dry = self.var_dry_run.get()
    if dry:
      self._log("warn", "🧪 DRY RUN MODE: No git commands will be executed.")

    changed_repos: List[str] = []
    warn_repos: List[Tuple[str, str]] = []
    error_repos: List[Tuple[str, str]] = []

    total = len(repos)
    for idx, r in enumerate(repos, start=1):
      if self._worker_stop.is_set():
        self._log("warn", f"🛑 Stop requested; stopping after {idx - 1} of {total} repo{'' if total == 1 else 's'}.")
        break

      repo_path = path_safe(str(r.get("path", "") or ""))
      ssh_key = path_safe(str(r.get("ssh_key", "") or ""))

      self._ui_q.put(("status", f"Pulling... ({idx} of {total} repo{'' if total == 1 else 's'})"))

      # Mark pulling + update last-seen
      seen_iso = now_iso()
      upsert_repo(manifest, repo_path, phase="pulling", message="Pulling...", seen_at=seen_iso, last_error="")
      self._repo_state_by_path[repo_path] = repos_by_path(manifest).get(repo_path, RepoState(path=repo_path))  # refresh mapping
      self._ui_q.put(("tree_update_by_repo", (repo_path, ssh_key, "Pulling...", ts_short(seen_iso), ts_short(str(r.get("pulled_at", "") or "")))))

      if dry:
        self._log("info", f"🟡 [Dry Run] Would pull: {repo_path} (SSH key: {ssh_key})")
        upsert_repo(manifest, repo_path, phase="idle", message="Dry run", seen_at=seen_iso)
        self._repo_state_by_path[repo_path] = repos_by_path(manifest).get(repo_path, RepoState(path=repo_path))
        self._ui_q.put(("tree_update_by_repo", (repo_path, ssh_key, "Dry run", ts_short(seen_iso), ts_short(str(r.get("pulled_at", "") or "")))))
        continue

      success, error_msg, changed = git_pull_ff_only(repo_path, ssh_key)

      if not success and error_msg:
        em = (error_msg or "").lower()

        # Non-error "skipped" states (YELLOW)
        if "unborn" in em or "no commits" in em:
          msg = "Unborn HEAD (no commits)"
          self._log("warn", f"🟨 {repo_path} - {msg}.")
          warn_repos.append((repo_path, msg))

          upsert_repo(manifest, repo_path, phase="skipped", message="Unborn (no commits)", seen_at=seen_iso, last_error="")
          self._repo_state_by_path[repo_path] = repos_by_path(manifest).get(repo_path, RepoState(path=repo_path))
          self._ui_q.put(("tree_update_by_repo", (repo_path, ssh_key, "Unborn (no commits)", ts_short(seen_iso), ts_short(str(r.get("pulled_at", "") or "")))))

        elif "bare repository" in em or "no work tree" in em or "work tree" in em:
          msg = "Bare repository (no work tree)"
          self._log("warn", f"🟨 {repo_path} - {msg}.")
          warn_repos.append((repo_path, msg))

          upsert_repo(manifest, repo_path, phase="skipped", message="Bare repo (no work tree)", seen_at=seen_iso, last_error="")
          self._repo_state_by_path[repo_path] = repos_by_path(manifest).get(repo_path, RepoState(path=repo_path))
          self._ui_q.put(("tree_update_by_repo", (repo_path, ssh_key, "Bare repo (no work tree)", ts_short(seen_iso), ts_short(str(r.get("pulled_at", "") or "")))))

        else:
          # Real error (RED)
          self._log("fail", f"❌ {repo_path} - {error_msg}")
          error_repos.append((repo_path, error_msg))

          upsert_repo(manifest, repo_path, phase="error", message="Error", seen_at=seen_iso, last_error=error_msg)
          self._repo_state_by_path[repo_path] = repos_by_path(manifest).get(repo_path, RepoState(path=repo_path))
          self._ui_q.put(("tree_update_by_repo", (repo_path, ssh_key, "Error", ts_short(seen_iso), ts_short(str(r.get("pulled_at", "") or "")))))

      else:
        pulled_iso = now_iso()

        if changed:
          self._log("ok", f"✅ {repo_path} - Updated.")
          changed_repos.append(repo_path)
          upsert_repo(manifest, repo_path, phase="done", message="Updated", seen_at=seen_iso, pulled_at=pulled_iso, last_error="")
          self._ui_q.put(("tree_update_by_repo", (repo_path, ssh_key, "Updated", ts_short(seen_iso), ts_short(pulled_iso))))
        else:
          self._log("ok", f"✅ {repo_path} - Done (no changes).")
          upsert_repo(manifest, repo_path, phase="done", message="Done (no changes)", seen_at=seen_iso, pulled_at=pulled_iso, last_error="")
          self._ui_q.put(("tree_update_by_repo", (repo_path, ssh_key, "Done (no changes)", ts_short(seen_iso), ts_short(pulled_iso))))

        self._repo_state_by_path[repo_path] = repos_by_path(manifest).get(repo_path, RepoState(path=repo_path))

      # Persist v2 manifest as we go (crash-safe progress)
      if not dry:
        save_manifest_v2(path_safe(repo_list_path), manifest, dry_run=False)

      self._ui_q.put(("progress", min(1.0, idx / max(1, total))))

    self._log("info", "------------------------------------------------------------")
    self._log("info", "RESULT")
    self._log("info", "------------------------------------------------------------")

    self._log("info", "Repositories with changes pulled:")
    if changed_repos:
      for rr in changed_repos:
        self._log("ok", f"  ✅ {rr}")
    else:
      self._log("warn", "  (none)")

    self._log("info", "")
    self._log("info", "Repositories skipped (non-error):")
    if warn_repos:
      for rr, msg in warn_repos:
        self._log("warn", f"  🟨 {rr} - {msg}")
    else:
      self._log("warn", "  (none)")

    self._log("info", "")
    self._log("info", "Repositories with errors:")
    if error_repos:
      for rr, msg in error_repos:
        self._log("fail", f"  ❌ {rr} - {msg}")
    else:
      self._log("warn", "  (none)")

    self._log("info", "------------------------------------------------------------")
    self._log("ok", "END PULL")
    self._log("info", "------------------------------------------------------------")


def main() -> int:
  # Must happen early for best taskbar behavior on Windows.
  set_windows_app_user_model_id(APP_USER_MODEL_ID)

  # Set theme BEFORE creating the CTk root.
  ctk.set_appearance_mode("dark")
  ctk.set_default_color_theme("blue")

  app = App()
  app.mainloop()
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
